package com.anjing.model.request;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class GlobalRequestContext
{
    // Request id generated by frontend, gateway, or backend.
    private String requestId;

    // Trace id propagated across future service calls.
    private String traceId;

    // Tenant id for future multi-tenant projects.
    private String tenantId;

    // Current user id.
    private String userId;

    // Current user display name.
    private String userName;

    // Current user role list from upstream auth or gateway.
    private String userRoles;

    // Caller id for service-to-service calls.
    private String callerId;

    // Locale from Accept-Language.
    private String locale;

    // User or client time zone.
    private String timeZone;

    // Client ip.
    private String ip;

    // Request url.
    private String url;

    // Request method: GET/POST/DELETE/PUT.
    private String methodType;

    // Controller or service class.
    private String className;

    // Controller or service method.
    private String methodName;

    // Method arguments.
    private Object[] args;

}
